# Ansible playbook for a Drupal server.
- hosts: default
  gather_facts: yes
  sudo: true
  vars_files:
  - vars/main.yml
  tasks:
  - include: tasks/locale.yml
  - include: tasks/sysutils.yml
  - include: tasks/php.yml
  handlers:
  - include: handlers/main.yml

