Vagrant.configure("2") do |config|
  config.vm.box = "precise32"
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioning/playbook.yml"
    ansible.sudo = true
    #ansible.inventory_path = "provisioning/inventory"
  end
  config.vm.network :forwarded_port, host: 4567, guest: 80
end
